- backend/src/main/java/com/mybuddy/global/audit/Auditable.java
- backend/src/main/java/com/mybuddy/global/audit/CreateAuditorAware.java
- backend/src/main/java/com/mybuddy/global/utils/ApiMultiResponse.java
- backend/src/main/java/com/mybuddy/global/utils/PageInfo.java
global utils: ApiMultiResponse(multi response dto) 와 pageInfo
global audit: Auditable 과 CreateAuditorAware
> [추가] Global ApiMultiResponse, PageInfo, Auditable, CreateAuditorAware 추가 (2023.03.09 정다운)

- backend/src/main/java/com/mybuddy/MyBuddyApplication.java
MyBuddyApplication 클래스에 @EnableJpaAuditing 추가
> [기타] Auditable 사용 위해 필요한 애너테이션  수정 (2023.03.10 정다운)

- backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
- backend/src/main/java/com/mybuddy/global/auth/dto/LoginDto.java
- backend/src/main/java/com/mybuddy/global/auth/filter/JwtAuthenticationFilter.java
- backend/src/main/java/com/mybuddy/global/auth/filter/JwtVerificationFilter.java
- backend/src/main/java/com/mybuddy/global/auth/handler/MemberAccessDeniedHandler.java
- backend/src/main/java/com/mybuddy/global/auth/handler/MemberAuthenticationEntryPoint.java
- backend/src/main/java/com/mybuddy/global/auth/handler/MemberAuthenticationFailureHandler.java
- backend/src/main/java/com/mybuddy/global/auth/handler/MemberAuthenticationSuccessHandler.java
- backend/src/main/java/com/mybuddy/global/auth/jwt/JwtTokenizer.java
- backend/src/main/java/com/mybuddy/global/auth/userdetails/MemberDetailsService.java
- backend/src/main/java/com/mybuddy/global/auth/utils/ErrorResponder.java
- backend/src/main/java/com/mybuddy/global/auth/utils/MemberAuthorityUtils.java
- backend/src/main/java/com/mybuddy/global/exception/LogicException.java
- backend/src/main/java/com/mybuddy/global/exception/LogicExceptionCode.java
- backend/src/main/java/com/mybuddy/global/utils/ErrorResponse.java
- backend/src/main/java/com/mybuddy/member/entity/Member.java
- backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
- backend/src/main/resources/application.yml
상기 제목과 같이 추가하여 PR 올립니다.
보안 관련 코드는 보안 적용이 안된 상태로 실행 가능한 정도까지 주석 처리 되어있으니 로컬로 pull 해서 제대로 실행되는지 점검 해보시고 merge했으면 합니다.
> [추가] Jwt 보안 기능 / Exception / Error 관련 코드 추가 (2023.03.09 강지후)

- backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
- backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
- backend/src/main/java/com/mybuddy/bulletin_post/entity/BulletinPost.java
- backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
- backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostRepository.java
- backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
> [추가] BulletinPost CRUD (2023.03.10 정다운)

- backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
- backend/src/main/java/com/mybuddy/global/utils/ApiMultiResponse.java
ApiMultiResponse 양식 수정( status, message, data, pageInfo ) 이에 따른 BulletinPostController 수정
> [수정] ApiMultiResponse 양식 수정, 이에 따른 BulletinPostController 수정 (2023.03.10 정다운)

- backend/src/main/java/com/mybuddy/amenity/entity/Amenity.java
- backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
연관관계 매핑 실수한것 1:N으로 변경해 테스트까지 완료했습니다! 
감사합니다 다운님👍
> [버그] Amentiy-BulletinPost 매핑 실수 해결 (1:N)

- backend/src/main/java/com/mybuddy/global/exception/StorageException.java
- backend/src/main/java/com/mybuddy/global/storage/FileSystemStorageService.java
- backend/src/main/java/com/mybuddy/global/storage/S3StorageService.java
- backend/src/main/java/com/mybuddy/global/storage/StorageService.java
- backend/src/main/java/com/mybuddy/member/controller/MemberController.java
- backend/src/main/java/com/mybuddy/member/dto/MemberCreateDto.java
- backend/src/main/java/com/mybuddy/member/dto/MemberListResponseDto.java
- backend/src/main/java/com/mybuddy/member/dto/MemberResponseDto.java
- backend/src/main/java/com/mybuddy/member/dto/MyAmenityDto.java
- backend/src/main/java/com/mybuddy/member/entity/Member.java
- backend/src/main/java/com/mybuddy/member/mapper/MemberMapper.java
- backend/src/main/java/com/mybuddy/member/service/MemberService.java
- backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
Member 2차 작업 이슈 #13 의 내용과 같이 완료했습니다.
중요한 작업으로는 크게
1. MultipartFile 저장 로직 추가
2. 연관 관계 매핑 1차 반영
3. mapper에 myBulletinPosts와 myAmenities 매핑 반영
> [추가/수정] MultipartFile 저장 로직 추가, 연관 관계 매핑, mapper 및 entity 수정

- frontend/src/styles/GlobalStyles.js
변경사항
- GlobalStyles에 기존에 적용되어 있던 scss 변수 삭제
- css 상수 적용
> [수정] GlobalStyles파일 scss 변수 삭제 및 css 변수 적용

- backend/src/main/java/com/mybuddy/amenity/repository/AmenityCustomRepositoryImpl.java
- AmenityCustomRepositoryImpl에 존재하는 BulletinPostMapper 제거
> [버그] bean 생성 오류 해결, 사용되지 않는 mapper 제거

- backend/src/main/java/com/mybuddy/comment/controller/CommentController.java
- backend/src/main/java/com/mybuddy/comment/dto/CommentCreateDto.java
- backend/src/main/java/com/mybuddy/comment/dto/CommentUpdateDto.java
- backend/src/main/java/com/mybuddy/comment/entity/Comment.java
- backend/src/test/java/com/mybuddy/comment/controller/CommentControllerTest.java
- backend/src/test/java/com/mybuddy/global/mockdata/MockTestData.java
> [추가] CommentControllerTest (Create,Update,Delete)

- frontend/src/components/UI/Card/Card.jsx
- frontend/src/components/UI/MypageProfile.jsx
개발사항
- profile 컴포넌트 개발
- feed item과 구분을 위해 MypagePrfile로 수정
- Card  컴포넌트 border 상수 적용
> [추가 / 수정] profile 컴포넌트 개발, card css border 상수 적용 (2023.03.13 정정수)

- backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
bulletinPost mapper 수동매핑 완료, like 매핑은 추후 수정 예정
> [수정] bulletinPost mapper 수동매핑 완료, like 매핑은 추후 수정 예정  (2023.03.13 정다운)

- backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
다른 엔티티 연결에 따른 bulletinPost dto 주석 해제
> [수정] bulletinPost dto 주석 해제 (2023.03.13 정다운)

- backend/src/main/java/com/mybuddy/bulletin_post/entity/BulletinPost.java
- backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
BulletinPost 일부 주석 해제, 
BulletinPostService 2차 수정(3차 수정 필요)
> [수정] BulletinPost 일부 주석 해제, BulletinPostService 2차 수정 (2023.03.14 정다운)

- backend/src/main/java/com/mybuddy/amenity/mapper/AmenityMapper.java
- backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
- backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
- backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
> [리팩토링/버그] Amenity Mapper에 존재하는 중복 메서드 제거, Member null 임시 해결 

- backend/src/main/java/com/mybuddy/amenity/repository/AmenityCustomRepository.java
- backend/src/main/java/com/mybuddy/amenity/repository/AmenityCustomRepositoryImpl.java
- backend/src/main/java/com/mybuddy/amenity/service/AmenityService.java
- backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepository.java
- backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
어제 말씀드렸던대로 CustomBulletinPostRepositoryImpl 생겨서 이동시켜놨습니다.
> [리팩토링] amenity 패키지가 갖고있던 tagged BulletinPost 관련 로직 bulletin-post로 이동

- backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
- backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
- backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
- backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepository.java
- backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
- backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostRepository.java
- backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
bulletinPost 도메인 3차 수정(follow와 like 제외한 구현  완료) 
포스트맨 테스팅 완료
json 업데이트 완료
> [수정] bulletinPost 도메인 3차 수정(follow와 like 제외한 구현  완료) (2023.03.14 정다운)

- backend/src/docs/asciidoc/index.adoc
- backend/src/main/java/com/mybuddy/amenity/controller/AmenityController.java
- backend/src/main/java/com/mybuddy/amenity/entity/Amenity.java
- backend/src/main/java/com/mybuddy/amenity/mapper/AmenityMapper.java
- backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
- backend/src/test/java/com/mybuddy/amenity/controller/AmenityControllerTest.java
- backend/src/test/java/com/mybuddy/global/mockdata/MockTestData.java
index.adoc에 comment 작성된 부분이 commit이 안되어있어 지금 같이 올렸습니다.
> [추가] AmenityControllerTest & API 문서화

- frontend/src/components/Feeds/Feed/ProfileItem.jsx
- frontend/src/components/Feeds/Feeds.jsx
- frontend/src/components/Feeds/FeedsTitle.jsx
- frontend/src/components/UI/Dropdown/DropdownFriend.jsx
- frontend/src/components/UI/SearchInput/SearchInput.jsx
- frontend/src/hooks/useDropdown.js
- frontend/src/hooks/useInputs.js
개발 내용
- profileItem  background-img -> img tag로 변경 
-  alt속성 활용하기 위해서 변경 
- feeds grid의 columns 너비 props 추가
- 친구 검색과 home 공통화를 위해 사용 
- 친구 검색창 개발
- [닉네임, 강아지] 이름 필터추가
- 검색창 개발
- inputs hook 추가
버그 수정
- dropdown: form에서 사용되는 경우 새로고침 발생하지 않도록 수정
> [수정/추가] Feed profileItem  수정, 친구 검색창 추가 (2023.03.16 정정수)

- frontend/src/Pages/FriendSearchPage.jsx
- frontend/src/Pages/HomePage.jsx
- frontend/src/Router.js
- frontend/src/components/Feeds/FeedsTitle.jsx
개발내용
- feed title logo 친구찾기시 조건부 랜더링 추가
- 홈 컴포넌트 title 오타 수정
- 친구찾기 페이지 라우터 추가
- 친구찾기 화면 개발
> [추가/수정] 친추찾기 화면 개발, 홈(피드) 타이틀 오타 수정 ( 2023.03.16 정정수 )

- frontend/src/Pages/FriendSearchPage.jsx
- frontend/src/Pages/HomePage.jsx
- frontend/src/components/Feeds/Feed/PostItem.jsx
- frontend/src/components/Feeds/Feeds.jsx
- frontend/src/components/Feeds/FeedsTitle.jsx
- frontend/src/components/UI/Dropdown/DropdownFriend.jsx
##개발내용
- Home 화면 창 크기에 내용 작아지게 수정
- @media 설정
> [수정] Home 화면 관련 페이지들 @media 설정 (2023.03.16 왕지호)

- frontend/src/Pages/FriendSearchPage.jsx
- frontend/src/Pages/HomePage.jsx
- frontend/src/Pages/UserAboutmePage.jsx
- frontend/src/components/Feeds/Feed/PostItem.jsx
- frontend/src/components/Feeds/Feeds.jsx
- frontend/src/components/Feeds/FeedsTitle.jsx
- frontend/src/components/Layout/Header.jsx
- frontend/src/components/UI/SearchInput/SearchInput.jsx
- Userpage 버튼 경로마다 다르게 수정
- Header 친구찾기에 Navlink 설정
- Home, Friendsearch page 컴포넌트 사이즈 수정, 삐그덕 거리는거 수정... / 이미지 추가
- Friendsearch page 검색창 @media 삭제, 검색창이 줄어드는걸로 수정
> [수정] Userpage 버튼 / Header Navlink / 홈,친구페이지 

- backend/src/main/java/com/mybuddy/follow/dto/FollowResponseDto.java
- backend/src/main/java/com/mybuddy/follow/service/FollowServiceImpl.java
- backend/src/main/java/com/mybuddy/global/exception/LogicExceptionCode.java
- backend/src/test/java/com/mybuddy/follow/controller/FollowControllerTest.java
- backend/src/test/java/com/mybuddy/follow/repository/FollowRepositoryTest.java
- backend/src/test/java/com/mybuddy/follow/service/FollowServiceTest.java
- backend/src/test/java/com/mybuddy/global/mockdata/MockTestData.java
아래의 커밋 리스트와 같이 작업하여 PR을 올립니다. 3개의 커밋은 간단한 수정이나 리팩토링인데 나머지 1개가 이 PR에서 제일 중요한 Follow 테스트 코드이니 이를 중점으로 리뷰 해주시면 되겠습니다.
> [추가] #106 Follow 테스트 추가 (2023.03.16 강지후)

- backend/src/main/java/com/mybuddy/amenity/controller/AmenityController.java
- backend/src/main/java/com/mybuddy/amenity/service/AmenityService.java
- backend/src/main/java/com/mybuddy/bulletin_post/entity/BulletinPost.java
- backend/src/test/java/com/mybuddy/amenity/controller/AmenityControllerTest.java
- backend/src/test/java/com/mybuddy/amenity/service/AmenityServiceTest.java
- backend/src/test/java/com/mybuddy/global/mockdata/MockTestData.java
테스트 코드에 사용될 BulletinPost를 위해 
AllArgumentConstuctor를 제거하고, @Builder를 추가했습니다.
> [추가] AmenityService 슬라이스 테스트

- frontend/package.json
- frontend/public/mockServiceWorker.js
- frontend/src/index.js
- frontend/src/mocks/browser.js
- frontend/src/mocks/data/member.js
- frontend/src/mocks/handlers.js
- frontend/src/mocks/resolvers/member.resolvers.js
- frontend/yarn.lock
개발내용
- msw를 이용한 로컬 api 테스트 추가
- api 정의
- 로그인:  POST '/api/v1/auth/login'
- 임의에 auth 헤더 반환 
- 로그아웃: POST '/api/v1/auth/logout'
- 토큰필요 
- 회원가입: POST '/api/v1/members'
- 회원탈퇴: DELETE '/api/v1/members' 
- 토큰필요 
- 마이페이지: GET '/api/v1/members/:memberId'
- 마이페이지 수정: PATCH '/api/v1/members/:memberId')
- 토큰필요
사용방법
- msw내 정의된 url을 이용하여 패칭
```jsx
fetch('/api/v1/auth/login', {
method: 'POST',
body: JSON.stringify({ email: 'test@example.com', password: 'password' }),
})
.then(response => response.json())
.then(data => console.log(data));
fetch('/api/v1/members', {
method: 'POST',
body: JSON.stringify({
email: 'test@example.com',
password: 'password!123',
nickname: 'r',
dogName: '123123123132r',
dogGender: '남자',
}),
})
.then(response => response.json())
.then(data => console.log(data));
```
> [추가] member 로컬 테스트를 위해 msw 추가 (2023.03.17 정정수)

- backend/src/test/java/com/mybuddy/global/config/TestWebMvcConfig.java
- backend/src/test/java/com/mybuddy/global/interceptor/HttpServletRequestInterceptor.java
> [버그] 인터셉터 추가로 발생한 테스트코드 버그 해결 - 테스트 설정 추가 (2023.03.20 강지은)

- backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
- backend/src/main/java/com/mybuddy/follow/controller/FollowController.java
- backend/src/main/java/com/mybuddy/follow/repository/FollowCustomRepository.java
- backend/src/main/java/com/mybuddy/follow/repository/FollowCustomRepositoryImpl.java
- backend/src/main/java/com/mybuddy/follow/service/FollowService.java
- backend/src/main/java/com/mybuddy/follow/service/FollowServiceImpl.java
- backend/src/main/java/com/mybuddy/global/config/AdminConfig.java
- backend/src/main/java/com/mybuddy/global/interceptor/LoginUserInterceptor.java
- backend/src/main/java/com/mybuddy/member/controller/MemberController.java
- backend/src/main/java/com/mybuddy/member/entity/Member.java
- backend/src/main/java/com/mybuddy/member/mapper/MemberMapper.java
- backend/src/main/java/com/mybuddy/member/service/MemberService.java
- backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
- backend/src/main/java/com/mybuddy/search/mapper/SearchMapper.java
- backend/src/test/java/com/mybuddy/follow/controller/FollowControllerTest.java
- backend/src/test/java/com/mybuddy/follow/repository/FollowRepositoryTest.java
- backend/src/test/java/com/mybuddy/follow/service/FollowServiceTest.java
- backend/src/test/java/com/mybuddy/global/mockdata/MockTestData.java
- backend/src/test/java/com/mybuddy/member/controller/MemberControllerTest.java
- backend/src/test/java/com/mybuddy/member/service/MemberServiceTest.java
로그인 인터셉터 추가에 따라서 코드가 변경되었고, Admin 관련한 config가 추가되었습니다.
브랜치 이름과 달리 Follow 쪽 코드에도 로그인 멤버 확인 로직이 추가되었으니 참고 바랍니다.
> [수정/추가] 로그인 인터셉터 추가에 따른 코드 변경/AdminConfig 추가 (2023.03.20 강지후)

- backend/src/main/java/com/mybuddy/email/controller/EmailController.java
- backend/src/main/java/com/mybuddy/email/dto/EmailDto.java
- backend/src/main/java/com/mybuddy/email/service/EmailService.java
- backend/src/main/java/com/mybuddy/email/service/EmailServiceImpl.java
- 비지니스용 gmail 계정을 이용해 메일을 전송합니다.
> [추가] 비밀번호 변경을 위한 이메일 전송 (2023.03.21 강지은)

- backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
- backend/src/main/java/com/mybuddy/follow/repository/FollowCustomRepositoryImpl.java
- backend/src/main/java/com/mybuddy/follow/service/FollowServiceImpl.java
- backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
- backend/src/main/java/com/mybuddy/global/service/CompositeService.java
- getBulletinPost 생성 실패 버그
- 팔로워가 아닌 사람의 게시글이 피드에 노출되는 버그
- 팔로우 삭제 실패 버그
> [버그/기타] 전체 요청 테스트 후 발생한 버그 해결, SpringSecurity 권한 주석 해제 (2023.03.21 강지은)

- backend/src/main/java/com/mybuddy/global/exception/LogicExceptionCode.java
- backend/src/main/java/com/mybuddy/search/service/SearchService.java
회원 검색시 type dogName/nickname 아닐경우 
Type not found 404 응답으로 수정해두었습니다.
> [수정] 회원 검색 에러 응답 수정 (2023.03.22 정다운)

- frontend/src/Pages/HomePage.jsx
- frontend/src/components/Feeds/FeedList.jsx
- frontend/src/components/FriendSearch/FriendSearchList.jsx
- frontend/src/components/UI/PostItem/index.jsx
- frontend/src/components/UI/PostProfileItem/index.jsx
- frontend/src/hooks/useObserverFetch.js
개발내용
- 리엑트의 ref 설정 오류로 2회 이상의 무한스코릴이 확장되지 않는 현상 수정
- 각 배열의 마지막 요소에서 패칭되는 오류 수정 
-  마지막 페이지의 마지막 요소시 서버 요청하도록 수정
> [버그] 무한스크롤 버그 수정 (2023.03.22 정정수)

- backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
✅ SecurityConfig
> 로그에 대해 세세한 정보를 볼 수 있는 @EnableWebSecurity(debug = true)를 추가했는데 과하다고 생각될 경우 나중에 제거해도 됩니다.
> [추가] CORS 문제 1차 해결 (2023.03.24 강지은)

- backend/build.gradle
- backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
- backend/src/main/java/com/mybuddy/global/config/AwsConfig.java
- backend/src/main/java/com/mybuddy/global/service/CompositeService.java
- backend/src/main/java/com/mybuddy/global/storage/FileSystemStorageService.java
- backend/src/main/java/com/mybuddy/global/storage/S3StorageService.java
- backend/src/main/java/com/mybuddy/global/storage/StorageService.java
- backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
- backend/src/main/resources/application.yml
S3 upload delete 기능 포함한 업로드 로직 추가 후
member service, bulletin service 관련 코드들 수정하였습니다.
> [추가/수정] S3업로드 코드 추가, 관련 수정 (2023.03.24 정다운)

- backend/build.gradle
- backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
- backend/src/main/java/com/mybuddy/global/auth/filter/JwtAuthenticationFilter.java
- multipartResolver : MultiPart 용량 10MB로 설정했습니다. 추후 용량은 협의후에 변경될 수 있습니다.
- 쿠키 (Refresh)에 Secure 설정
> [추가] multipartResolver : MultiPart 용량 설정, 쿠키(Refresh)에 Secure 설정 (2023.03.25 강지은)

- backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
- backend/src/main/java/com/mybuddy/comment/dto/CommentResponseDto.java
- backend/src/test/java/com/mybuddy/comment/controller/CommentControllerTest.java
> [수정] 댓글 응답에 프로필이미지 추가 및 테스트 코드 반영 (2023.03.26 강지은)

- backend/.gitignore
- backend/src/main/java/com/mybuddy/global/config/AdminConfig.java
- backend/src/main/resources/application-server.yml
상기 제목과 같이 추가 및 수정되었으니 PR 확인 바랍니다.
> [추가/수정] application-server.yml 추가/admin 계정 관련 버그 수정/.gitignore 수정 (2023.03.26 강지후)

- frontend/src/Pages/LoginPage.jsx
- frontend/src/Pages/SignupPage.jsx
- frontend/src/Pages/UserPage.jsx
- frontend/src/components/Follow/FollowModal.jsx
- frontend/src/components/Layout/Header.jsx
- Header 로그인 여부에 따라 조건부 렌더링, css 변경
- 친구찾기 selected 부분 userpage도 적용되게 구현
- login, signup page path 변경 (login-> home / signup-> login)
- 팔로잉 모달 내 팔로잉 리스트 카드 클릭 시 그 유제 페이지로 이동 구현
- userpage cureentusermemberId 적용
> [수정] Header, follow modal, memberId 적용, 수정 (2023.03.26 왕지호)

- backend/src/test/java/com/mybuddy/member/repository/MemberRepositoryTest.java
- backend/src/test/java/com/mybuddy/member/service/MemberServiceTest.java
Member 및 Follow 쪽에서는 이번에 추가한 테스트 이외에는 굳이 테스트 추가가 필요하지 않아 보여 여기까지 작업하여 PR 올립니다.
> [추가] findByEmail Method 추가에 따른 테스트 추가 (2023.03.27 강지후)

- frontend/src/Pages/PostDetailPage.jsx
- frontend/src/Pages/PostNewPage.jsx
- frontend/src/components/Comments/CommentsForm.jsx
- frontend/src/components/Comments/CommentsItem.jsx
- frontend/src/components/UI/EditAndRemoveButton/index.js
- post 댓글 관련 페이지들 수정
- 팝업메뉴 수정
> [수정] post 댓글 관련 페이지들 수정 (2023.03.27 왕지호)

- frontend/src/Pages/FriendSearchPage.jsx
- frontend/src/api/commentsApi.js
- frontend/src/components/Comments/CommentsItem.jsx
- frontend/src/components/Comments/CommentsList.jsx
- frontend/src/components/Comments/index.jsx
- frontend/src/components/FriendSearch/FriendSearchHeader.jsx
- frontend/src/components/FriendSearch/FriendSearchList.jsx
- frontend/src/components/UI/EditAndRemoveButton/index.jsx
- frontend/src/hooks/comments/useDeleteComments.js
- frontend/src/hooks/comments/useUpdateComments.js
- 게시글 상세 기능 추가
- 댓글 수정 기능 추가
- 댓글 삭제 기능 추가
- 친구 찾기 화면 기능 변경
- 검색 옵션 기본값 지정
- 사용자 ux를 고려하여 검색 옵션 위치 변경
> [추가, 수정] 게시글 수정, 삭제 기능 추가 (2023.03.27 정정수)

- frontend/src/Pages/PostNewPage.jsx
- frontend/src/api/userApi.js
- frontend/src/components/PostDetail/PostDetailHeader.jsx
- frontend/src/hooks/members/useGetMembersInfo.js
개발내용
- user API를 통해 기본 정보를 받아 게시글 생성폼에 입력되도록 수정
- 게시글 생성, 취소 버튼 hover 색상 추가
> [추가/수정] user 정보 받기 추가, 버튼 hover color 추가 (2023.03.27 정정수)

- frontend/src/Pages/PostDetailPage.jsx
- frontend/src/api/bulletinPostsApi.js
- frontend/src/api/userApi.js
- frontend/src/assets/icons/icon-see-more-small.svg
- frontend/src/components/Comments/CommentsItem.jsx
- frontend/src/components/Comments/index.jsx
- frontend/src/components/PostDetail/PostDetailHeader.jsx
- frontend/src/components/PostDetail/index.jsx
- frontend/src/components/UI/EditAndRemoveButton/index.jsx
- frontend/src/hooks/bulletinPosts/useDeleteBulletinPost.js
- frontend/src/hooks/bulletinPosts/useUpdateBulletinPost.js
- frontend/src/hooks/useMap.js
- 게시글 삭제기능 추가
- 게시글 상세 헤더의 edit 메뉴 조건부 렌더링 추가
- 로그인 id와 동일한 경우만 display 
- 댓글 edit 메뉴 조건부 렌더링 추가
- 로그인 id와 동일한 경우만 display
> [수정/추가] 게시글 삭제 기능 추가, 수정 버튼 조건부 렌더링 추가

- frontend/src/Pages/AmenityPage.jsx
- frontend/src/Pages/UserPlacePage.jsx
- frontend/src/Router.js
- frontend/src/api/placeApi.js
- frontend/src/api/userApi.js
- frontend/src/components/Feeds/PlaceFeedList.jsx
- frontend/src/components/Feeds/index.jsx
- frontend/src/components/KakaoMap/KakaoMap.jsx
- frontend/src/components/KakaoMap/LocationMap.jsx
- frontend/src/components/Place/PlaceHeader.jsx
- frontend/src/components/User/ImageUpload.jsx
- amenity page(mypage place click하면 나오는 피드 페이지) 생성
- amenity 관련 페이지들 수정
- 지도 draggable: true로 수정
- imageupload button 위치 수정
> [추가, 수정] amenity page 생성, 관련 페이지들 수정 / 지도, 이미지업로더 수정

- backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
- backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
> [추가] bulletinPost 피드 응답에 createdAt 필드 추가 (2023.03.28 정다운)

- frontend/src/Pages/PostNewPage.jsx
- frontend/src/components/Comments/CommentsForm.jsx
- frontend/src/components/Comments/index.jsx
- frontend/src/components/PostDetail/PostDetailHeart.jsx
- frontend/src/components/PostDetail/index.jsx
- frontend/src/components/PostEdit/index.jsx
- frontend/src/components/UI/Modal/ModalBase.jsx
- frontend/src/hooks/useAxiosErrorModal.js
- 다른 페이지와 일관성을 유지하기 위해 버튼 통일
- 애니매이션 닫기로 인해 버튼 두 개인 경우 오동작이 발생하여 조건부로 수정
- axios 오류처리 모달 공통화 처리
> [수정] 모달 버튼 통일, 애니메션 닫기 조건부로 수정 (2023.03.29 정정수)

- frontend/src/components/PostEdit/index.jsx
- frontend/src/components/UI/Modal/ModalBase.jsx
- 게시글 수정시 이미지 변경 인식 못하는 문제 수정
- 서버 변경에 따른 기본값 null 지정
> [버그] 게시글 수정 이미지 인식 오류, 기본값  null 지정

- frontend/src/components/FriendSearch/FriendSearchHeader.jsx
- frontend/src/hooks/useMap.js
- 이슈: #215 
- 게시글 등록 지도의 마커 이미지 수정
- 친구찾기 드롭다운 순서 변경
> [수정] 마커 이미지 수정, 친구 찾기 검색 옵션 수정

- backend/src/test/java/com/mybuddy/amenity/controller/AmenityControllerTest.java
> [수정] AmenityControllerTest 코드 수정 (2023.03.29 강지후)

- frontend/src/components/PostDetail/PostDetailnfo.jsx
- frontend/src/components/PostEdit/PostEditlnfo.jsx
- frontend/src/components/UI/PostProfileItem/index.jsx
- frontend/src/components/UI/UserProfile/index.jsx
- frontend/src/hooks/useImageError.js
개발사항
- 이슈: #217 
- 프로파일 이미지가 없거나 불로오기 실패한 경우 기본 이미지로 출력되도록 수정
> [추가] 프로파일 기본 이미지 지정 (2023.03.29 정정수)

- frontend/src/Pages/InfoPage.jsx
- frontend/src/Router.js
- frontend/src/components/Info/ColorCard.jsx
- frontend/src/components/Info/ColorLargeCard.jsx
- frontend/src/components/Info/InfoCard.jsx
- frontend/src/components/Info/MyBuddyInfoCard.jsx
- frontend/src/components/Layout/Header.jsx
- info page 관련페이지들 문구, css 수정
- 로그인 여부에 따라서 home/info page 나오게 설정
> [수정] info 관련 페이지들 수정 (2023.03.29 왕지호)

- frontend/src/Pages/InfoPage.jsx
- frontend/src/components/Info/MyBuddyInfoCard.jsx
- info page에 들어가는 gif dlalwl cnrk
- gif 들어가는 컴포넌트들 수정
> [추가, 수정] info page 구현 gif 추가, 관련 페이지들 수정 (2023.03.29 왕지호)

- backend/src/main/java/com/mybuddy/amenity/entity/Amenity.java
- backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
- backend/src/main/java/com/mybuddy/bulletin_post/entity/BulletinPost.java
- backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
- backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
- backend/src/main/java/com/mybuddy/global/service/CompositeService.java
bulletinPost create 시 amenity Null값도 저장되도록 정
> [수정] bulletinPost create 에서 amenity 버그 수정 (2023.03.29 정다운)

- frontend/src/components/Follow/FollowerModal.jsx
> [수정] 팔로워 카드 높이 수정

- frontend/src/components/PostDetail/PostDetailHeart.jsx
- frontend/src/data/FEED_DETAIL_DUMY.js
- frontend/src/mocks/browser.js
- frontend/src/mocks/handlers.js
- frontend/src/mocks/resolvers/member.resolvers.js
- frontend/src/mocks/resolvers/posts.resolvers.js
버그 내용
- 이슈: #213 
- 원인: 좋아요 버튼 클릭 3초내 팝업 닫은 경우, 언마운트에서 마지막 최신 좋아요 상태를 정상적으로 받지못하여 발생
조치 내용
- react useRef를 이용하여 좋아요 상태 값을 저장하도록 수정
- 테스트를 위한 likes mock 추가
> [버그] 게시글 좋아요 클릭 버그 수정 (2023.03.31 정정수)

- frontend/src/Pages/PostNewPage.jsx
- frontend/src/components/PostDetail/PostDetailHeart.jsx
- frontend/src/data/FEED_DETAIL_DUMY.js
- frontend/src/hooks/useImageError.js
- frontend/src/mocks/browser.js
- frontend/src/mocks/handlers.js
- frontend/src/mocks/resolvers/member.resolvers.js
- frontend/src/mocks/resolvers/posts.resolvers.js
- 게시글 상세의 위치정보를 선택으로 수정
Resolved: #235
> [수정] 게시글 등록의 위치정보 미필수로 변경 (2023.03.31 정정수)

- frontend/src/App.js
- frontend/src/Pages/PostNewPage.jsx
- frontend/src/components/PostNew/PostNewMap.jsx
- frontend/src/components/PostNew/PostNewPlaceList.jsx
- frontend/src/components/UI/Modal/ModalBase.jsx
- frontend/src/hooks/useMap.js
- 검색 결과 리스트의 마우스 오버시 마커 이동에서 클릭시로 변경
- 마우스 오버로 이동시 불필요한 지도 이동으로 피로감이 느껴짐
- 더 불러오기 버튼추가
- 검색 결과가 1회 15개로 검색되어 최대 검색결과인 45개를 수집할 수 있도록 더 불러오기 이벤트 추가
- 현지도에서 재검색 버튼 추가 
- 특정 영역내로 한정하지 않으면 검색하기 어렵다고 판단되어 추가
> [수정] 게시글 등록 지도 리팩토링 (2023.03.31 정정수)

- backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
> [버그] 팔로우 한 유저들의 게시물 피드 순서 버그 해결 (2023.03.31 강지은)

- frontend/src/Pages/PlacePage.jsx
- frontend/src/Pages/PostDetailPage.jsx
- frontend/src/Pages/PostEditPage.jsx
- frontend/src/Pages/PostNewPage.jsx
- frontend/src/Pages/UserAboutmePage.jsx
- frontend/src/components/Info/InfoCard.jsx
- frontend/src/components/KakaoMap/LocationMap.jsx
- frontend/src/components/KakaoMap/SearchModal.jsx
- frontend/src/components/User/ImageUpload.jsx
- info page members github link 추가
- 지도 페이지 이미지 남아있는 버그 수정, searchmodal keyword placeholder 추가
- 회원정보 이미지 변경 jpeg 확장자 추가
- postne, postdetail, postedit card media 사용 scale 변경
- follow 상태 수정
> [버그, 수정] infopage githublink 추가, 지도 페이지 버그/텍스트 수정, 이미지 변경 확장자 jpeg 추가, 게시글 크기 조정, 팔로우 버그 수정 (2023.03.31 왕지호)

- frontend/src/components/Comments/CommentsItem.jsx
- frontend/src/components/PostDetail/PostDetailnfo.jsx
- frontend/src/components/PostEdit/PostEditlnfo.jsx
- frontend/src/components/UI/UserProfile/index.jsx
개발내용
- 이슈: #217
- 댓글 프로필 기본이미지 추가
- alt 속성 변경
- `${nickname} 프로필 사진`으로 변경
> [수정] 댓글 프로필 기본이미지 추가, alt 변경 (2023.04.01 정정수)

- frontend/src/components/Feeds/FeedList.jsx
- frontend/src/components/Feeds/PlaceFeedList.jsx
- frontend/src/components/UI/PostItem/index.jsx
- frontend/src/components/UI/PostList/index.jsx
개발내용
- 이슈: #246 
- 최대화시 하단 그림자 없어짐 버그 수정
-  margin bottom 추가
- 닉네임 줄바꿈 현상 수정
- 최대 너비 수정
- 미디어 쿼리 위치 수정
> [버그/수정] 하단 그림자 짤림현상 해결, 미디어 쿼리 수정 (2023.04.01 정정수)

- frontend/src/Pages/UserAboutmePage.jsx
- frontend/src/Pages/UserEditPage.jsx
- frontend/src/Pages/UserFeedPage.jsx
- frontend/src/Pages/UserPage.jsx
- frontend/src/Pages/UserPlacePage.jsx
- frontend/src/components/User/ImageUpload.jsx
- frontend/src/components/User/UserEditContent.jsx
- frontend/src/components/User/UserEditHeader.jsx
- frontend/src/components/User/UserHeader.jsx
- frontend/src/components/User/UserInfoComponent.jsx
- frontend/src/components/User/UserProfileImg.jsx
- frontend/src/components/User/UserTabMenu.jsx
- 마이페이지, 유저페이지, 수정페이지 높이 줄어들 떄 잘리는 버그 수정
> [버그] 마이페이지, 유저 페이지 관련 페이지들 높이 잘리는 문제 수정 (2023.04.01 왕지호)

- frontend/src/Pages/PostDetailPage.jsx
- frontend/src/Pages/PostEditPage.jsx
- frontend/src/components/Comments/CommentsForm.jsx
- frontend/src/components/Comments/CommentsItem.jsx
- frontend/src/components/Comments/index.jsx
- frontend/src/components/Feeds/index.jsx
- frontend/src/components/PostDetail/PostDetailContent.jsx
- frontend/src/components/PostDetail/PostDetailHeart.jsx
- frontend/src/components/PostDetail/index.jsx
- frontend/src/components/PostNew/PostNewPlaceList.jsx
- frontend/src/components/UI/ImageUploadButton.jsx
- frontend/src/components/UI/LoginRequestModal/index.jsx
- frontend/src/components/UI/Modal/Modal.jsx
- frontend/src/components/UI/Modal/ModalNonContent.jsx
- frontend/src/components/UI/UserName/index.jsx
- frontend/src/hooks/useAxiosErrorModal.js
- frontend/src/styles/shared.jsx
- 관련 이슈 
- #252 
- #250
- 좋아요, 댓글 입력시 비로그인시 서버에 전송하지 않도록 변경
- 좋아요 비로그인시 상태변경 삭제
- 비로인 상태로 좋아요, 댓글 입력 요청시 바로 로그인 요청 모달 발생하도록 변경
- 그 외 scroll none, FlexJustifyAlignCenter 변수화 적용
> [버그/수정] 좋아요, 댓글 권한확인 추가, 게시글 상세 스크롤 추가(2023.04.01 정정수)

- frontend/src/Pages/UserAboutmePage.jsx
- frontend/src/Pages/UserEditPage.jsx
- frontend/src/Pages/UserFeedPage.jsx
- frontend/src/Pages/UserPage.jsx
- frontend/src/Pages/UserPlacePage.jsx
> [버그] 유저 페이지 관련 버그 수정 (2023.04.01 왕지호)

- backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
- backend/src/main/java/com/mybuddy/global/service/CompositeService.java
- backend/src/main/java/com/mybuddy/member/repository/MemberCustomRepository.java
- backend/src/main/java/com/mybuddy/member/repository/MemberCustomRepositoryImpl.java
- backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
> [버그] 최신 회원 페이지네이션 (2023.04.01 강지은)

- frontend/src/Pages/AmenityPage.jsx
- frontend/src/Pages/PostDetailPage.jsx
- frontend/src/Pages/PostEditPage.jsx
- frontend/src/Pages/PostNewPage.jsx
- frontend/src/components/Feeds/FeedList.jsx
- frontend/src/components/Feeds/PlaceFeedList.jsx
- frontend/src/components/Feeds/index.jsx
- frontend/src/components/Layout/Header.jsx
- frontend/src/components/PostDetail/PostDetailContent.jsx
- frontend/src/components/PostEdit/PostEditContent.jsx
- frontend/src/components/PostNew/PostNewMap.jsx
- frontend/src/components/PostNew/PostNewlnfo.jsx
- frontend/src/components/UI/PostHeader/index.jsx
- frontend/src/components/UI/PostItem/index.jsx
- frontend/src/styles/shared.jsx
- 관련 이슈: #260 
- 게시글 상세, 수정, 등록 팝업 너비, 높이에 따른 Scale 적용
- 게시글의 본문 영역 flex 높이 적용 (최소 180px)
- 불필요 중복 css 삭제
- Place Feeds 컴포넌트의 불필요 전달인자 amenityId 삭제
> [수정/버그] 게시글 상세, 수정, 등록 팝업 화면 크기별 scale 적용 (2023.04.02 정정수)

- frontend/src/Pages/UserAboutmePage.jsx
- frontend/src/api/userApi.js
- frontend/src/components/Feeds/FeedList.jsx
- frontend/src/components/PostEdit/index.jsx
- frontend/src/components/UI/Loading.jsx
- 홈(Feed) 로딩 중 로딩 텍스트 출력 추가
- 로딩텍스트 화면 중앙배치로 수정
- 팔로우 버그 수정
> [수정/버그] 홈(Feed) 로딩 중 텍스트 출력 추가, 팔로우 버그 수정 (2023.04.02 정정수)

- frontend/src/Pages/ImagePage.jsx
- frontend/src/Pages/UserEditPage.jsx
- frontend/src/Pages/UserPage.jsx
- frontend/src/components/UI/Modal/Modal.jsx
- frontend/src/components/User/ImageUpload.jsx
- frontend/src/components/User/UserEditContent.jsx
- frontend/src/components/User/UserHeader.jsx
- frontend/src/components/User/UserInfoComponent.jsx
- frontend/src/components/User/UserProfileImg.jsx
- frontend/src/hooks/useUserInuput.js
- frontend/src/hooks/useUserUpdate.js
- imageupload 크기가 이미지에 따라서 변경되는 현상 수정
- modal에 meadia 추가(shred에 올려주신거 사용)
- userpage 관련 컨텐츠들 media 적용, 비율 수정
- useredit page hooks 분리
> [버그, 수정, 추가] 이미지 비율, modal media, userpage, imgae page logo, useredit page 관련 수정/추가 (2023.04.02 왕지호)

- frontend/src/components/PostDetail/index.jsx
- frontend/src/components/PostEdit/index.jsx
- 게시글 상세 null에 따른 조건부 렌더링 추가
- 게시글 수정 null에 따른 예외처리 추가
> [수정/버그] 게시글 위치 정보 null 예외처리 추가 (2023.04.03 정정수)

- frontend/src/Pages/FriendSearchPage.jsx
- frontend/src/Pages/PostNewPage.jsx
- frontend/src/components/FriendSearch/FriendSearchDefault.jsx
- 친추 찾기 로딩 텍스트 추가
- 게시글 생성 후 게시글 리스트 리프래시 추가
- 게시글 리스트에 내 게시물 추가에 따른 변경
> [수정] 게시글 생성시 게시글 리스트 refresh 추가, 친구 찾기 로딩 추가 (2023.04.03 정정수)

- frontend/src/Pages/UserAboutmePage.jsx
- frontend/src/Pages/UserEditPage.jsx
- frontend/src/api/bulletinPostsApi.js
- frontend/src/components/UI/Modal/Modal.jsx
- frontend/src/components/User/UserProfileImg.jsx
- 불필요 콘솔 로그 삭제
- 마이페이지 이미지의 영역 벗어남 현상으로  aspect-ratio 추가
> [수정] 불필요 로그 삭제,  마이페이지 aspect-ratio 추가 (2023.04.03 정정수)

- frontend/src/components/FriendSearch/index.jsx
- 친구찾기 페이지의 리스트에 불필요한 좌우 스크롤 삭제
> [버그] 친구찾기 페이지 좌우 스크롤 삭제

- frontend/src/Pages/UserPlacePage.jsx
- 장소찾기와 마이페이지 url이 상이하여 오류 발생하여 동일하게 수정
> [버그] 마이페이지 장소클릭 버그 수정 (2023.04.03 정정수)

- backend/src/main/java/com/mybuddy/global/advice/PerformanceAdvice.java
컨트롤러 핸들러 메서드에 도달하는 요청 처리 시간을 로그에 기록합니다.
> [추가] PerformanceAdvice (2023.04.07 강지은)

- backend/src/main/java/com/mybuddy/MyBuddyApplication.java
PerformanceAdvice 추가 하면서 AOP 설정을 위한 어노테이션(@EnableAspectJAutoProxy)이 함께 커밋되지 않은것을 확인해 추가했습니다.
> [기타] AOP 설정 어노테이션 (2023.04.09 강지은)
