backend/build.gradle

제목과 같이 build.gradle에 추가적으로 dependency를 추가하였습니다. 현재는 유효성 검사 annotation도 삽입이 안 돼서 validation이나 restDocs 등의 의존성을 추가했고 빌드 및 실행이 되는 것을 확인했습니다.
본격적으로 작업에 들어가기 전에 빨리 셋업이 되는 것이 좋을 것 같아서 바로 PR 올립니다.

[병합] #5 build.gradle에 관련 의존성 추가 (2023.03.07 강지후)

---

frontend/src/components/UI/Button.js
frontend/src/components/UI/HeaderButton.js

- 버튼 컴포넌트 추가
- 헤더 버튼 컴포넌트 추가
- 결이 다른거 같아서 헤더에 위치한 버튼이랑 일반 버튼이랑 나눠서 컴포넌트 작업을 했는데 과연 이게 맞는지, 합치는게 맞는지...

[추가] 일반 버튼, 헤더 버튼 컴포넌트 생성 (2023.03.10 왕지호)

---

backend/src/main/java/com/mybuddy/amenity/controller/AmenityController.java
backend/src/main/java/com/mybuddy/amenity/dto/AmenityResponseDto.java
backend/src/main/java/com/mybuddy/amenity/repository/AmenityCustomRepository.java
backend/src/main/java/com/mybuddy/amenity/repository/AmenityCustomRepositoryImpl.java
backend/src/main/java/com/mybuddy/amenity/service/AmenityService.java

게시글에 많이 태그 된 추천장소리스트 반환 (위치 필터링)을 적용했습니다. 
요청시 반환하는 json 정보는 다음과 같습니다. 
```json
{
"code": "200",
"message": "지역에서 추천하는 장소 리스트입니다.",
"data": [
{
"amenityId": 2,
"addressId": 1472202212355221,
"amenityName": "강아지놀이터",
"address": "서울 광진구 어딘가 주소입니다.",
"longitude": 126.12834637823106,
"latitude": 126.12834637823106,
"bulletinPostCount": 18
},
{
"amenityId": 1,
"addressId": 1472202213554222321,
"amenityName": "어딘가 장소인데 뭐라하지",
"address": "서울 광진구 어딘가 주소입니다.",
"longitude": 126.57647863723106,
"latitude": 126.57647863723106,
"bulletinPostCount": 5
}
]
}
```

[추가] 게시글에 많이 태그 된 추천장소리스트 반환 (위치 필터링)

---

backend/src/docs/asciidoc/index.adoc
backend/src/main/java/com/mybuddy/member/controller/MemberController.java
backend/src/main/java/com/mybuddy/member/dto/MemberPatchDto.java
backend/src/main/java/com/mybuddy/member/entity/Member.java
backend/src/main/java/com/mybuddy/member/repository/MemberRepository.java
backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
backend/src/test/java/com/mybuddy/global/config/TestConfig.java
backend/src/test/java/com/mybuddy/global/mockdata/MockTestData.java
backend/src/test/java/com/mybuddy/member/controller/MemberControllerTest.java
backend/src/test/java/com/mybuddy/member/repository/MemberRepositoryTest.java
backend/src/test/java/com/mybuddy/member/service/MemberServiceTest.java
backend/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
backend/src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
backend/src/test/resources/org/springframework/restdocs/templates/request-part-fields.snippet

이번 PR에서 가장 중요한 작업은 Member 관련 테스트 추가입니다.
현재 MultipartFile과 관련된 테스트는 post 밖에 되지 않으므로 patchMemberTest()는 주석 처리 되어있습니다. 추후 방법이 결정되면 주석을 풀고 알맞게 수정이 될 예정입니다.
제가 바로 머지하지 않고 있을테니 리뷰어들께서 한 번 살펴보셨으면 합니다.
나머지는 아래의 commit 목록을 참고 바랍니다.

[추가/수정] #42 Member 관련 테스트 추가 / Service 메서드 로직 수정 (2023.03.11 강지후)

---

backend/src/main/java/com/mybuddy/amenity/controller/AmenityController.java
backend/src/main/java/com/mybuddy/amenity/dto/AmenityWithBulletinPost.java
backend/src/main/java/com/mybuddy/amenity/mapper/AmenityMapper.java
backend/src/main/java/com/mybuddy/amenity/repository/AmenityCustomRepository.java
backend/src/main/java/com/mybuddy/amenity/repository/AmenityCustomRepositoryImpl.java
backend/src/main/java/com/mybuddy/amenity/service/AmenityService.java
backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
backend/src/main/java/com/mybuddy/comment/controller/CommentController.java
backend/src/main/java/com/mybuddy/comment/mapper/CommentMapper.java

✅ 일단 작동하는 코드를 추가해놓았습니다. 효율성에 의해 설계를 약간 변경후 리팩토링할 예정입니다.
- BulletinPost가 페이징처리되어 지속적으로 요청이 오는데, 장소 정보를 계속 조회하면 효율성이 ⬇️ 👎
- Amenity 1개 조회,  AmenityId로 BulletinPostList를 조회하는 로직상 분리가 필요할 듯합니다.
- 나중에 bulletinPost custom repository 생성되면 수정이 필요합니다.
현재 반환하는 데이터는 다음과 같은 형태를 갖고 있는데 
Amenity와 BulletinPost를 분리하지 않을 경우  ApiMultiResponse를 바로 사용할 수 없어 
응답데이터를 약간 변경하게 되었는데요, 이 역시 설계가 변경되어야 함을 느낀 이유 중 하나입니다.
```json
{
"code": "200",
"message": "장소와 그 장소가 태그된 게시물들 반환",
"data": {
"addressId": 1472201342221,
"amenityName": "장소1",
"address": "서울 노원구 어딘가 주소입니다.",
"longitude": 126.12834637823106,
"latitude": 126.12834637823106,
"bulletinPosts": [
{
"bulletinPostId": 1,
"photoUrl": "/photoUrl/blah/blah/blah",
"postContent": "게시물 1 !!"
},
{
"bulletinPostId": 2,
"photoUrl": "/photoUrl/blah/blah/blah", …
```

[추가] 특정 장소와 태그된 게시글들 페이지네이션 처리해 반환

---

backend/src/main/java/com/mybuddy/global/exception/LogicExceptionCode.java
backend/src/main/java/com/mybuddy/member/repository/MemberCustomRepository.java
backend/src/main/java/com/mybuddy/member/repository/MemberCustomRepositoryImpl.java
backend/src/main/java/com/mybuddy/member/repository/MemberRepository.java
backend/src/main/java/com/mybuddy/member/service/MemberService.java
backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
backend/src/test/java/com/mybuddy/member/repository/MemberRepositoryTest.java
backend/src/test/java/com/mybuddy/member/service/MemberServiceTest.java

아래와 같이 update 되었습니다.
1. Member entity 자체의 유효성 검사를 사용하기 전 예외 처리를 위해 verifyIfNicknameExists()를 추가.
2. MemberRepository 대신 MemberCustomRepository로 query를 받도록 변경. (queryDsl 사용)

[추가/수정] 닉네임 중복 여부 확인 메서드 추가/query 방법 변경 (2023.03.13 강지후)

---

backend/src/main/java/com/mybuddy/comment/repository/CommentCustomRepository.java
backend/src/main/java/com/mybuddy/comment/repository/CommentCustomRepositoryImpl.java
backend/src/main/java/com/mybuddy/comment/service/CommentService.java

GET api/v1/bulletin-posts/1로 응답 json잘 돌아오는 것 확인했습니다.
```json
{
"code": "200",
"message": "게시물 1개 조회",
"data": {
"bulletinPostId": 1,
"photoUrl": "/Users/kangjieun/IdeaProjects/seb42_main_011/USER - SIGN IN.png",
"postContent": "게시물4 !!",
"createdAt": "2023-03-15T16:13:11.12849",
"memberId": 1,
"nickname": "코딩김",
"dogName": "왕밤톨",
"profileUrl": null,
"amenityId": 1,
"amenityName": "장소2",
"likeCount": 1,
"likeByUser": 2,
"commentList": [
{
"commentId": 2,
"commentContent": "우와 콩이가 너무 귀여워요",
"memberId": 1,
"nickName": "코딩김",
"dogName": "왕밤톨"
},
{
"commentId": 3,
"commentContent": "우와 콩이가 너무 귀여워요zzzzzz",
"memberId": 1,
"nickName": "코딩김",
"dogName": "왕밤톨"
},
{
"commentId": 4,
"commentContent": "우와 콩이가 너무 귀여워요zzzzzzasdsads",
"memberId": 1,
"nickName": "코딩김",
"dogName": "왕밤톨"
},
{
"commentId": …
```

[수정] comment findByBulletinPostId 적용

---

backend/src/main/java/com/mybuddy/amenity/entity/Amenity.java
backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
backend/src/main/java/com/mybuddy/comment/entity/Comment.java

FeedResponse에는 반영하지 않았습니다. 
FeedResponse에서는 댓글 정보를 안가져가고(null), 댓글의 개수만 반환하는게 좋을것 같습니다.  
id전략 AUTO와 IDENTITY 전략이 크게 다를게 없지만, 
테스트상에서 id가 2번부터 생성되는 오류 해결 및 추후 RDS로 Mysql을 사용할 것을 생각해 Identity로 변경하였습니다.

[수정/기타] 게시글 상세보기에서 댓글 최신순 (desc) 반환, id전략 변경

---

backend/src/docs/asciidoc/index.adoc
backend/src/main/java/com/mybuddy/member/controller/MemberController.java
backend/src/main/java/com/mybuddy/member/dto/MemberInfoResponseDto.java
backend/src/main/java/com/mybuddy/member/mapper/MemberMapper.java

추가 내용은 아래와 같습니다.
1. 회원 구분을 위한 API ```/api/v1/members/{member-id}/info```
2. 이메일 혹은 닉네임으로 중복 검사하는 API ```/api/v1/members/check```

[추가/수정] 회원 구분 및 중복 검사 API 추가 / RestDocs 수정 (2023.03.24 강지후)

---

backend/src/main/java/com/mybuddy/global/auth/controller/AuthController.java
backend/src/main/java/com/mybuddy/global/auth/filter/JwtAuthenticationFilter.java

Refresh Token 전송 방법을 쿠키로 변경하였고 Postman으로 테스트까지 하였습니다. Pull 받으셔서 서버에 적용해서 테스트 해보시기 바랍니다.

[수정] Refresh Token 전송 방법 쿠키로 변경 (2023.03.24 강지후)

---

backend/src/main/java/com/mybuddy/email/controller/EmailController.java
backend/src/main/java/com/mybuddy/email/service/EmailService.java
backend/src/main/java/com/mybuddy/email/service/EmailServiceImpl.java
backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
backend/src/main/java/com/mybuddy/global/auth/filter/JwtVerificationFilter.java
backend/src/main/java/com/mybuddy/global/auth/jwt/JwtTokenizer.java
backend/src/main/java/com/mybuddy/global/config/InterceptorConfig.java
backend/src/main/java/com/mybuddy/global/interceptor/LoginUserInterceptor.java
backend/src/main/java/com/mybuddy/member/controller/PasswordController.java
backend/src/main/java/com/mybuddy/member/dto/MemberPrivacyDto.java
backend/src/main/java/com/mybuddy/member/service/MemberService.java
backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java

- 이메일 전송시 토큰을 생성해 버튼 url에 추가했습니다.
- 해당 토큰을 이용해 비밀번호 재설정 요청을 보내면, 정상적으로 변경되는것을 확인했습니다.
- 토큰의 만료기한은 현재 24시간으로 되어있는데 추후 수정될 수 있습니다.

[수정/추가] 이메일 전송시 URL+토큰,  비밀번호 재설정 (2023.03.24 강지은)

---

backend/src/main/java/com/mybuddy/global/auth/filter/JwtAuthenticationFilter.java

SameSite=None을 추가했는데 실제로 동작할지는 모르겠습니다. Secure=true로 해줘야 제대로 작동한다는데 저 옵션은 Https를 위한 것이라 저 옵션은 빼고 SameSite에 대한 것만 일단 추가해서 올립니다.

[추가] Refresh Token 쿠키에 SameSite=None 추가 (2023.03.24 강지후)

---

backend/build.gradle
backend/src/main/resources/application-h2.yml
backend/src/main/resources/application-mysql.yml
backend/src/main/resources/application.yml

현재 application.yml 파일 설정을 각자 하고 있어서 통일이 안되는 관계로, 이 PR을 올립니다.
application.yml에는 공통 부분이 들어있고, application-h2.yml 및 application-mysql.yml로 나누어 놨으니 필요에 따라 active profile을 변경하여 쓰시면 되고, 환경변수로 되어 있는 부분은 환경변수로 써도 되고 그냥 각자 로컬에서 하드코딩으로 쓰셔도 될 것 같습니다. build.gradle에는 h2와 mysql을 같이 주석처리 없이 열어놨는데, profile을 나눠서 사용하면 빌드도 되고 실행도 되는 것을 확인하였습니다.
PR 확인해보시고 적용해도 되겠다 싶으면 merge가 가능하다고 알려주시기 바랍니다.

[추가] Local용 application.yml profile 추가 (2023.03.25 강지후)

---

backend/src/main/java/com/mybuddy/global/advice/GlobalExceptionAdvice.java
backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
backend/src/main/java/com/mybuddy/global/storage/S3StorageService.java

업로드 파일 (.png  .jpg  .gif) 로 제한,
이 외에 파일 업로드시 400 bad request 예외 처리,
업로드 파일 용량 yml 파일로도 제한 가능해서 SecurityConfig에 해당 bean 삭제,
업로드 파일 용량 초과시 413 request entity too large 예외처리
해두었습니다.

[추가] 업로드 파일 확장자 제한, 예외처리, 용량 예외처리 (2023.03.26 정다운)

---

.github/workflows/client.yml

개발사항
- 테스트 완료전까지 불필요한 배포를 방지하기 위해 dev에서 fe/feat/deploy 브랜치로 수정

[수정] 테스트를 위해 Frontend 배포기준 브랜치 임시 수정 (2023.03.27 정정수)

---

frontend/src/Pages/FriendSearchPage.jsx
frontend/src/components/UI/PostProfileItem/index.jsx

- 이슈번호: #208 
- home 피드의 게시글 리스트 아이템과 분리 과정에서 잘 못된 필드명 설정으로 이미지 주소를 정상적으로 설정하지 못함
- photoUrl -> profileUrl로 변수 및 파라미터명 변경

[버그] 친구찾기 이미지 출력 버그 수정 (2023.03.29 정정수)

---

frontend/src/Pages/FriendSearchPage.jsx
frontend/src/components/Comments/CommentsForm.jsx
frontend/src/components/Comments/CommentsItem.jsx
frontend/src/components/UI/PostProfileItem/index.jsx

- 이슈: #210 
- 댓글 영역의 최대 너비를 지정하지 않아 내용이 영역을 벗어나는 현상 발생
- 그에 따른 수정/삭제하기 메뉴 영역 위치 깨짐현상 발생
- 최대 너비 지정
- 최대 row 3줄 까지 출력하고, 댓글 전체 너비가 반응형으로 줄어든 경우 (...) 생략 표시하도록 수정
- 댓글 작성 form의 최대 글자수 120자로 제한 -> 현재 댓글 영역의 최대 너비일때 3줄의 글자수
- 수정/삭제하기 메뉴 반응형으로 수정

[버그] 글자 수에 따른 댓글 영역 벗어남 버그 수정 (2023.03.29 정정수)

---

frontend/src/utils/time.js

개발내용
- 현재 서버 기준시가 영국시로 되어있어, +9시간을 더하여 home feed에 출력되도록 수정

[수정] 배포 환경에 맞춰 9시간 시차 적용 (2023.03.29 정정수)

---

backend/src/main/java/com/mybuddy/follow/service/FollowServiceImpl.java
backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
backend/src/main/java/com/mybuddy/global/auth/filter/JwtAuthenticationFilter.java
backend/src/main/java/com/mybuddy/member/service/MemberService.java
backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
backend/src/test/java/com/mybuddy/follow/service/FollowServiceTest.java

현재 탈퇴 회원은 로그인이 되지 않지만 FE에 에러 메시지가 전달되지 않고 500 코드만 보내주는 상태입니다. 이것은 추후에 수정이 될 것입니다.

[추가/수정] 탈퇴 회원 관련 로그인 및 팔로우 추가 및 수정

---

frontend/src/hooks/useImageError.js

개발 내용
- 이슈: #217
- 프로필 url이 null인 경우 처리되지 않는 버그현상
- null인경우 기보이미지로 설정하도록 수정

[버그] 프로필 이미지 초기값으로 설정 (2023.03.30 정정수)

---

frontend/src/components/PostDetail/PostDetailnfo.jsx
frontend/src/components/PostDetail/index.jsx
frontend/src/utils/time.js

- 이슈 
- #229
- #230 
- 게시글 상세의 프로필 이름 클릭시 상세이동
- 삭제시 게시글 리스트 리패칭하도록 수정

[수정] 게시글 삭제시 리프레시, 프로필 이름 클릭시 친구페이지 이동 (2023.03.30 정정수)

---

frontend/src/components/UI/PostItem/index.jsx
frontend/src/components/UI/PostList/index.jsx

- 관련 이슈: #246 
- 변경 적용한 CSS에서 게시글이미지는 공백 생김 현상 발생하여 제거
- card 영역 높이 수정

[버그] 홈(피드) 이미지 하단 빈공간 제거, 높이 수정 (2023.04.01 정정수)

---

backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepository.java
backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
backend/src/main/java/com/mybuddy/search/mapper/SearchMapper.java
backend/src/main/java/com/mybuddy/search/repository/SearchCustomRepository.java
backend/src/main/java/com/mybuddy/search/repository/SearchCustomRepositoryImpl.java
backend/src/main/java/com/mybuddy/search/repository/SearchRepository.java
backend/src/main/java/com/mybuddy/search/service/SearchService.java

로그인 유저 게시물 피드 조회시 자신의 게시물까지 조회 가능하도록 수정했습니다.
회원 검색시 admin 계정 조회 가능하던 버그 admin 조회 불가능하도록 (memberId 1 조회 불가능하도록) 수정해두었습니다.

[수정] 게시물 피드 조회시 로그인 유저 게시물까지 조회, admin계정 조회 버그 수정 (2023.04.02 정다운)

---

backend/build.gradle

버전을 1.0.0으로 수정하였습니다.
빌드 해보니 버전이 알맞게 나오는 것도 확인하였습니다.

[기타] build.gradle의 앱 버전 1.0.0으로 수정 (2023.04.02 강지후)

---

backend/src/main/java/com/mybuddy/member/mapper/MemberMapper.java

- 특정 유저에게서 마이페이지 500에러가 발생하였고, AmenityResponseDtos 생성중 Exception을 뱉는것을 확인했습니다.
```java
List<AmenityForMyPageResponseDto> amenityForMyPageResponseDtos =
member.getBulletinPosts().stream()
.map(bulletinPost -> {
AmenityForMyPageResponseDto amenityForMyPageResponseDto =
AmenityForMyPageResponseDto.builder()
.amenityId(bulletinPost.getAmenity().getAmenityId())
.amenityName(bulletinPost.getAmenity().getAmenityName())
.address(bulletinPost.getAmenity().getAddress())
.photoUrl(bulletinPost.getPhotoUrl())
.postCreatedAt(bulletinPost.getCreatedAt())
.build();
return amenityForMyPageResponseDto;
})
```
- 위 코드에서 멤버의 모든 게시물을 탐색하는데, 
게시물에 장소태그가 null일경우 bulletinPost.getAmenity()에서 NPE가 발생할것으로 예상되었고
Null이 아닌경우를 필터링 처리하여 해결했습니다.

[버그] 마이페이지 장소 응답에서, 게시물에 장소 없는 경우를 위한 Null 필터링 (2023.04.03 강지은)

---

frontend/src/Pages/AmenityPage.jsx
frontend/src/Pages/FriendSearchPage.jsx
frontend/src/components/Feeds/PlaceFeedList.jsx

- 장소 게시글 리스트 화면여부 판단 useSearchParams로 수정
- 홈(피드)와 동일하게 유저 네임부분 클릭시 친구 마이페이지 이동으로 수정

[버그] 장소 게시글 리스트 헤더, 클릭 이벤트 오류 수정 (2023.04.03 정정수)

---

backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java

일차적으로 현재 서비스에서 유저에게 보이는 탈퇴 유저와 관련된 부분을 없애는게 필요하다 판단해 다음과 같은 작업을 진행했습니다.
- 게시글에 달린 댓글 중 탈퇴한 회원의 댓글은 안나오게
- 피드에 탈퇴한 회원의 게시글은 안나오게
- 특정 장소가 태그된 게시물 반환시, 탈퇴한 회원의 게시물 안나오게

[버그] UI상 보이는 탈퇴 유저의 정보 제거 (2023.04.04 강지은)
